import type { ImageConversionOutputFormat } from "@/lib/api/types";

export type ConversionPage = { slug: string; source: string; target: ImageConversionOutputFormat; title: string; description: string; heading: string; intro: string; notes: string[] };
export const conversionPages: ConversionPage[] = [
  { slug: "png-to-jpg", source: "PNG", target: "jpeg", title: "PNG to JPG Converter – Free Online Image Converter", description: "Convert PNG images to JPG online. Choose a background when transparent PNG images need a JPG output.", heading: "PNG to JPG Converter", intro: "Convert PNG images to widely compatible JPG files when a smaller photographic format is more useful.", notes: ["JPG does not support transparency, so transparent PNGs need a background color.", "JPG is useful for photographs and general sharing."] },
  { slug: "jpg-to-png", source: "JPG", target: "png", title: "JPG to PNG Converter – Free Online Image Converter", description: "Convert JPG images to PNG online for lossless PNG output and compatible workflows.", heading: "JPG to PNG Converter", intro: "Convert a JPG to PNG for workflows that require a PNG file.", notes: ["PNG output can be larger than the original JPG.", "Conversion cannot restore detail previously lost in the JPG."] },
  { slug: "png-to-webp", source: "PNG", target: "webp", title: "PNG to WebP Converter – Free Online Image Converter", description: "Convert PNG images to WebP online. WebP supports transparency and can reduce file size for modern web use.", heading: "PNG to WebP Converter", intro: "Convert PNG files to modern WebP images while preserving transparency where supported.", notes: ["WebP supports transparent areas.", "WebP is often a useful smaller format for web delivery."] },
  { slug: "webp-to-png", source: "WebP", target: "png", title: "WebP to PNG Converter – Free Online Image Converter", description: "Convert WebP images to PNG online for compatibility with PNG-based tools and workflows.", heading: "WebP to PNG Converter", intro: "Convert WebP to PNG when a workflow or editor needs a standard PNG file.", notes: ["PNG output may be larger than WebP.", "Dimensions remain unchanged during normal conversion."] },
  { slug: "avif-to-webp", source: "AVIF", target: "webp", title: "AVIF to WebP Converter – Free Online Image Converter", description: "Convert AVIF images to WebP online for broad browser and application compatibility while preserving transparency where supported.", heading: "AVIF to WebP Converter", intro: "Convert AVIF files to WebP for workflows that need a widely supported modern image format.", notes: ["WebP supports transparent areas.", "Converting does not increase the original image dimensions."] },
  { slug: "avif-to-png", source: "AVIF", target: "png", title: "AVIF to PNG Converter – Free Online Image Converter", description: "Convert AVIF images to PNG online for lossless output and compatibility with PNG-based tools.", heading: "AVIF to PNG Converter", intro: "Convert an AVIF image to PNG when an editor or workflow does not accept AVIF.", notes: ["PNG preserves transparency.", "PNG output can be substantially larger than AVIF."] },
  { slug: "avif-to-jpg", source: "AVIF", target: "jpeg", title: "AVIF to JPG Converter – Free Online Image Converter", description: "Convert AVIF images to JPG online for broad compatibility with photo tools and sharing services.", heading: "AVIF to JPG Converter", intro: "Convert AVIF photos to widely compatible JPG files.", notes: ["JPG does not support transparency, so transparent AVIF images need a background color.", "JPG is a lossy format intended for photographs and general sharing."] },
  { slug: "png-to-ico", source: "PNG", target: "ico", title: "PNG to ICO Converter – Free Online Icon Converter", description: "Convert PNG images to multi-size ICO files online for website and application icons.", heading: "PNG to ICO Converter", intro: "Create a practical multi-size ICO file from a PNG for websites and applications.", notes: ["Choose which icon sizes to include.", "FileMino avoids unnecessary upscaling for small source images."] },
  { slug: "ico-to-png", source: "ICO", target: "png", title: "ICO to PNG Converter – Free Online Image Converter", description: "Convert ICO files to PNG online and select an embedded icon size before downloading.", heading: "ICO to PNG Converter", intro: "Extract an embedded ICO frame into a normal PNG image.", notes: ["ICO files can contain several icon sizes.", "FileMino selects the largest embedded size by default, but you can choose another."] },
];
export function getConversionPage(slug: string) { return conversionPages.find((page) => page.slug === slug); }
